version: '3.8'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV
      - HOST
      - PORT
      - NUXT_PUBLIC_API_URL
    restart: unless-stopped
    container_name: podinu