version: '3.8'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_PUBLIC_API_URL=https://directus.ludwigloth.cloud
    restart: unless-stopped
    container_name: podinu