version: "3.8"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3555}:3000"
    env_file:
      - stack.env
    restart: unless-stopped
    container_name: punkte3
